def chatbot(user_input):
    responses = {
        # IT & Cybersecurity (Expanded)
        "what is python": "Python is a popular programming language for web, AI, and data science!",
        "what is an api": "API stands for Application Programming Interface. It lets apps talk to each other!",
        "what is cloud computing": "Cloud computing means storing and accessing data over the internet instead of a local computer.",
        "what is ethical hacking": "Ethical hacking is using hacking skills to find security weaknesses and fix them!",
        "what is artificial intelligence": "AI is technology that allows machines to learn and make decisions!",
        "what is a database": "A database is a structured way to store and manage data!",
        "what is frontend development": "Frontend is what users see on a website! HTML, CSS, and JavaScript make it happen.",
        "what is backend development": "Backend is the server side of a website! It handles logic, databases, and APIs.",
        "what is a full-stack developer": "A full-stack developer works on both frontend and backend!",
        "what is machine learning": "Machine learning is a type of AI that helps computers learn from data!",
        
        # Expanded IT & Cybersecurity
        "what is cybersecurity": "Cybersecurity is the practice of protecting systems, networks, and data from digital attacks.",
        "what is malware": "Malware is any software designed to harm a computer or network, like viruses or ransomware.",
        "what is a firewall": "A firewall is a security system that monitors and controls incoming and outgoing network traffic.",
        "what is phishing": "Phishing is when attackers try to trick people into revealing sensitive information, like passwords.",
        "what is a vpn": "A VPN (Virtual Private Network) creates a secure connection over the internet, protecting your privacy.",
        "what is encryption": "Encryption is the process of converting information into a code to prevent unauthorized access.",
        "what is two-factor authentication": "Two-factor authentication (2FA) adds an extra layer of security by requiring two forms of identification.",
        "what is a ddos attack": "A DDoS (Distributed Denial of Service) attack is when multiple computers overwhelm a server, making it unavailable.",
        "what is a hacker": "A hacker is someone who gains unauthorized access to systems or data, often for malicious purposes.",
        "what is ransomware": "Ransomware is a type of malware that locks your files and demands payment to unlock them.",
        "what is a trojan horse": "A Trojan horse is a type of malware that appears as a legitimate program but secretly harms your system.",
        "what is penetration testing": "Penetration testing (ethical hacking) involves simulating attacks to find vulnerabilities in systems.",
        "what is the dark web": "The dark web is part of the internet that's not indexed by search engines and is often used for illegal activities.",
        "what is an ip address": "An IP address is a unique identifier for a device on a network, like a phone or computer.",
        "what is a botnet": "A botnet is a network of infected computers controlled by a hacker to perform malicious tasks.",
        "what is social engineering": "Social engineering is manipulating people into giving up confidential information or access to systems.",
        "what is a security breach": "A security breach is an incident where unauthorized access is gained to systems or data.",
        "what is encryption key": "An encryption key is used to encode and decode data, ensuring that only authorized users can access it.",
        "what is a vulnerability": "A vulnerability is a weakness in a system that can be exploited by an attacker.",
        "what is a rootkit": "A rootkit is a type of malware that hides itself in a system, allowing attackers to maintain control without detection.",
        "what is a data breach": "A data breach is when sensitive, confidential, or protected information is accessed or disclosed without permission.",
        "what is a password manager": "A password manager securely stores and organizes your passwords, helping you avoid weak or repeated passwords.",
        "what is a bot": "A bot is an automated program designed to perform repetitive tasks, like web scraping or responding to users.",
        "what is a vpn kill switch": "A VPN kill switch cuts your internet connection if the VPN connection is lost, protecting your privacy.",
        "what is endpoint security": "Endpoint security protects devices like computers, phones, and tablets from cyber threats.",
        "what is a security token": "A security token is a physical device or software-based tool used for secure authentication, like two-factor authentication.",
        "what is a proxy server": "A proxy server acts as an intermediary between your device and the internet, helping to secure or anonymize your traffic.",
        "what is a honeypot": "A honeypot is a decoy system set up to attract hackers and study their methods without compromising real data.",
        "what is an exploit": "An exploit is a piece of code or method used to take advantage of a vulnerability in a system.",
        "what is a bug bounty": "A bug bounty is a program where companies reward individuals who find and report vulnerabilities in their systems.",
        "what is zero-day exploit": "A zero-day exploit is an attack that targets a vulnerability before the vendor has released a fix for it.",
        "what is a security patch": "A security patch is an update that fixes vulnerabilities in software or hardware to prevent attacks.",
        "what is a bot attack": "A bot attack occurs when malicious bots flood a server or website, often causing it to crash or become unresponsive.",
        "what is a keylogger": "A keylogger is software that records keystrokes, often used to steal personal information like passwords.",
        "what is a trojan virus": "A Trojan virus is a type of malware that disguises itself as legitimate software but performs harmful actions.",
        "what is a cyber attack": "A cyber attack is any deliberate action taken to damage or disrupt a computer system or network.",
        "what is a bug": "A bug is an error or flaw in software that causes it to behave unexpectedly or incorrectly.",
        "what is code injection": "Code injection is a vulnerability that allows an attacker to insert malicious code into a program.",
        "what is a script kiddie": "A script kiddie is an unskilled hacker who uses pre-written tools and scripts to attack systems.",
        "what is a cipher": "A cipher is an algorithm used for encryption and decryption of data to keep it secure.",
        "what is an exploit kit": "An exploit kit is a collection of tools that allows attackers to exploit vulnerabilities in software.",
        "what is threat intelligence": "Threat intelligence involves collecting and analyzing information to predict and prevent cyber threats.",
        "what is a botnet attack": "A botnet attack is when multiple compromised devices are used to launch a coordinated cyber attack, often DDoS.",
        
        # Additional IT & Cybersecurity Terms
        "what is cryptojacking": "Cryptojacking is when hackers secretly use your computer's power to mine cryptocurrency without your consent.",
        "what is a backdoor": "A backdoor is a hidden entry point into a system, often created by malware for remote control by an attacker.",
        "what is a man-in-the-middle attack": "A man-in-the-middle (MITM) attack occurs when an attacker intercepts and manipulates communication between two parties.",
        "what is a patch management": "Patch management is the process of updating software to fix security vulnerabilities and bugs.",
        "what is osint": "OSINT (Open Source Intelligence) is the process of collecting publicly available data for security analysis.",
        "what is a ransomware attack": "A ransomware attack locks your files and demands a ransom to release them, often affecting businesses and individuals.",
        "what is a privilege escalation": "Privilege escalation is when an attacker gains higher levels of access to a system than intended, often to execute malicious tasks.",
        "what is a sandbox": "A sandbox is an isolated environment used to test suspicious programs or code without affecting the main system.",
        "what is a whitelist": "A whitelist is a list of trusted entities or addresses that are allowed access to a system, network, or resource.",
        "what is a black hat hacker": "A black hat hacker is a malicious hacker who violates security for personal gain or to cause harm.",
        "what is a white hat hacker": "A white hat hacker is an ethical hacker who helps organizations identify and fix vulnerabilities.",
        "what is a gray hat hacker": "A gray hat hacker is someone who may violate ethical standards but does not have malicious intent.",
        "what is a trojan downloader": "A Trojan downloader is a type of malware that silently downloads and installs additional malicious software onto a system.",
        "what is an adware": "Adware is software that automatically displays or downloads unwanted ads, often slowing down your system.",
        "what is a crypto wallet": "A crypto wallet is a tool that stores cryptocurrencies like Bitcoin or Ethereum, allowing you to send, receive, and store them.",
        "what is a spear-phishing attack": "Spear-phishing is a targeted attempt to steal sensitive information by pretending to be a trustworthy entity, usually via email.",
        "what is endpoint detection and response (edr)": "EDR is a cybersecurity approach that monitors, detects, and responds to threats on devices like computers and smartphones.",
        "what is a digital signature": "A digital signature is an electronic signature used to authenticate the identity of a sender and ensure data integrity.",
        "what is a security audit": "A security audit is an evaluation of an organization's security policies, systems, and controls to identify vulnerabilities.",
        "what is a blockchain": "A blockchain is a decentralized, distributed ledger technology that securely records transactions across a network of computers.",
        "what is a usb security key": "A USB security key is a physical device used as a second factor in two-factor authentication for added security."
        "what is phishing": "Phishing is a type of cyber attack where attackers trick individuals into providing sensitive information like passwords or credit card details.",
        "what is a zero-day attack": "A zero-day attack exploits vulnerabilities in software that are unknown to the software vendor, leaving no time for defense before it happens.",
        "what is a man-in-the-middle (MITM) attack": "A MITM attack occurs when an attacker secretly intercepts and alters communication between two parties, making them unaware of the manipulation.",
        "what is spear-phishing": "Spear-phishing is a targeted form of phishing where attackers personalize their approach to a specific individual or organization.",
        "what is a denial of service (DoS)": "DoS attacks aim to make a machine or network resource unavailable to users by overwhelming it with traffic or requests.",
        "what is a distributed denial of service (DDoS)": "A DDoS attack is a DoS attack that uses multiple devices (often part of a botnet) to flood a system with malicious traffic.",
        "what is an ssl certificate": "SSL (Secure Sockets Layer) certificates encrypt the data transmitted between a website and its visitors, ensuring secure connections.",
        "what is a hash function": "A hash function converts data into a fixed-size string of characters, which is typically used in cryptography to store passwords securely.",
        "what is a botnet attack": "A botnet attack is when a group of compromised devices (a botnet) is used to perform large-scale attacks like DDoS.",
        "what is a vpn kill switch": "A VPN kill switch is a security feature that disconnects your internet if your VPN connection drops, preventing data leaks.",
        "what is a patch": "A patch is a software update designed to fix bugs, improve functionality, or enhance security by fixing vulnerabilities.",
        "what is social engineering": "Social engineering is the manipulation of individuals into divulging confidential information by exploiting human psychology rather than technology.",
        "what is a rootkit": "A rootkit is a set of software tools used by attackers to gain unauthorized access and maintain control over a computer system.",
        "what is two-factor authentication (2FA)": "2FA adds an extra layer of security by requiring two forms of identification to verify a user's identity, typically something you know (password) and something you have (phone or security key).",
        "what is a vulnerability scan": "A vulnerability scan is an automated process that identifies security flaws or weaknesses in a system or network.",
        "what is a security information and event management (SIEM)": "SIEM is a system used to collect and analyze security data from various sources to help detect, monitor, and respond to security threats.",
        "what is a bot": "A bot is an automated program that performs repetitive tasks, often used for data collection, automated responses, or malicious activities.",
        "what is an ip spoofing": "IP spoofing involves changing the source IP address in packet headers to impersonate another system and gain unauthorized access.",
        "what is a keylogger": "A keylogger is a type of malicious software that records keystrokes to steal sensitive information, like passwords and credit card numbers.",
        "what is data encryption": "Data encryption is the process of converting data into a secret code to prevent unauthorized access, keeping information secure.",
        "what is a ransomware attack": "A ransomware attack involves malware that locks a user's files and demands a ransom to unlock them.",
        "what is a security patch": "A security patch is an update designed to address specific security vulnerabilities in a system or application.",
        "what is email spoofing": "Email spoofing is when attackers send emails from a forged email address to impersonate someone else and carry out a malicious act, like phishing.",
        "what is a digital signature": "A digital signature is an electronic signature used to verify the authenticity and integrity of digital messages or documents.",
        "what is a session hijacking": "Session hijacking is when an attacker steals a valid session token to gain unauthorized access to a user's account or session.",
        "what is a digital certificate": "A digital certificate is an electronic document used to prove the ownership of a public key, typically issued by a trusted certificate authority.",
        "what is a public key infrastructure (PKI)": "PKI is a framework that uses public and private keys along with digital certificates to ensure secure communication over the internet.",
        "what is a security breach": "A security breach is an incident in which unauthorized access is gained to a system, network, or data, often resulting in data theft or loss.",
        "what is ransomware as a service (RaaS)": "RaaS is a business model where cybercriminals provide ransomware tools to other attackers for a profit, making ransomware attacks easier for anyone to carry out.",
        "what is the deep web": "The deep web is the part of the internet not indexed by traditional search engines, often consisting of databases and other resources not meant for public access.",
        "what is cryptographic key management": "Cryptographic key management involves the generation, storage, and protection of keys used for encryption and decryption processes in a secure manner.",
        "what is an attack vector": "An attack vector is a method or pathway used by an attacker to gain access to a network or system to exploit vulnerabilities.",
        "what is a threat actor": "A threat actor is any individual or group responsible for attempting to exploit or attack systems, networks, or data for malicious purposes.",
        "what is a fake wifi hotspot": "A fake Wi-Fi hotspot is a fraudulent Wi-Fi network set up by attackers to steal personal information from users who connect to it.",
        "what is a port scan": "A port scan is the act of probing a computer or network for open ports to discover potential vulnerabilities.",
        "what is spear phishing": "Spear phishing is a highly targeted form of phishing where attackers tailor their fraudulent messages to a specific individual or organization.",
        "what is a man-in-the-browser attack": "A man-in-the-browser attack is when an attacker uses malware to intercept and manipulate web browser activities, such as online banking sessions.",
        "what is a security token": "A security token is a physical or software-based device used for authentication, often for accessing secure systems or networks.",
        "what is application security": "Application security involves measures to prevent threats and vulnerabilities in software applications, ensuring they are secure from external attacks.",
        "what is a honeypot": "A honeypot is a decoy system set up to attract cybercriminals and study their behavior without compromising real data or systems.",
        "what is the dark web": "The dark web is a hidden part of the internet that can only be accessed using specific software, and it's often used for illegal activities like selling drugs or hacking services.",
        "what is brute force attack": "A brute force attack is when attackers try every possible combination to guess a password or encryption key until they succeed.",
        "what is sql injection": "SQL injection is a vulnerability that allows attackers to insert malicious SQL queries into an application's database, potentially giving them unauthorized access to data."

                # Additional IT & Cybersecurity Terms
        "what is a denial of service attack": "A DoS (Denial of Service) attack tries to make a service unavailable by overwhelming it with traffic.",
        "what is a root cause analysis": "Root cause analysis is the process of identifying the fundamental cause of a problem or issue.",
        "what is a zero trust model": "The Zero Trust model is a security concept that assumes no one, inside or outside the network, is trustworthy.",
        "what is a data lake": "A data lake is a centralized repository that stores all your structured and unstructured data at any scale.",
        "what is blockchain technology": "Blockchain technology is a decentralized system that securely records transactions across multiple computers.",
        "what is a network attack": "A network attack targets a network's infrastructure to disrupt services, steal data, or cause damage.",
        "what is a signature-based detection": "Signature-based detection identifies threats by comparing incoming traffic to known patterns or signatures of attacks.",
        "what is a behavior-based detection": "Behavior-based detection identifies threats by analyzing unusual activity or deviations from normal system behavior.",
        "what is a cybersecurity framework": "A cybersecurity framework provides guidelines and best practices for protecting information systems from security threats.",
        "what is a supply chain attack": "A supply chain attack targets a company by compromising its suppliers or third-party vendors to gain access to the target's systems.",
        "what is a botnet herder": "A botnet herder is a hacker who controls a botnet of infected devices to carry out cyber attacks.",
        "what is an attack surface": "An attack surface is the sum of all potential entry points an attacker can exploit in a system or network.",
        "what is a privilege access management": "Privilege Access Management (PAM) is a security strategy used to control and monitor access to sensitive resources.",
        "what is a vulnerability scanner": "A vulnerability scanner is a tool that automatically identifies weaknesses and security flaws in a system.",
        "what is data encryption at rest": "Data encryption at rest refers to encrypting data stored on a device to protect it when it's not in use.",
        "what is a security operation center (soc)": "A Security Operation Center (SOC) is a facility responsible for monitoring, detecting, and responding to security threats.",
        "what is advanced persistent threat (apt)": "An Advanced Persistent Threat (APT) is a prolonged and targeted cyber attack, often aimed at stealing sensitive information.",
        "what is a wiper malware": "Wiper malware is a type of malicious software designed to erase data on a computer or network, often causing irreversible damage.",
        "what is a mobile device management (mdm)": "Mobile Device Management (MDM) is a security solution that helps organizations manage and secure employees' mobile devices.",
        "what is an access control list (acl)": "An Access Control List (ACL) defines permissions for resources or services to control who can access them and what actions they can perform.",  
    }

    return responses.get(user_input.lower(), "I don't understand. Try asking something else!")

while True:
    user_text = input("You: ")
    if user_text.lower() == "exit":
        print("Bot: Goodbye! 👋")
        break
    print("Bot:", chatbot(user_text))
